Group/urls.py
'''
Created on Apr 9, 2013

@author: CCMT
'''
from django.conf.urls import patterns, url

urlpatterns = patterns('Group.views',
                       url(r'^$', 'group', name="group"),
                       url(r'^create/$', 'create_group', name="create-group"),
                       url(r'^contacts/upload/$', 'contacts_upload', name="contacts-upload"),
                       )

MassMail/urls.py
from django.conf.urls import patterns, include, url

from MassMail.forms import LoginForm


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'MassMail.views.home', name='home'),
    url(r'^signup/$', 'MassMail.views.signup', name='signup'),
    url(r'^logout/$', 'MassMail.views.logout', name='logout'),
    url(r'^contract/$', 'MassMail.views.contract', name='contract'),
    url(r'^group/', include('Group.urls')),
    url(r'^auth/$', 'django.contrib.auth.views.login', { 'template_name' : 'signup/login.html',
          'authentication_form' : LoginForm}, name='auth_login'),
 
    # url(r'^MassMail/', include('MassMail.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

Group/models.py
'''
Created on Apr 9, 2013

@author: CCMT
'''
import datetime
import time
import hashlib

from django.contrib.auth.models import User
from django.db import models


class Member(models.Model):
    
    GENDER_CHOICES = (('MALE', 'Male'),
                      ('FEMALE', 'Female'))
    
    user = models.ForeignKey(User)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(max_length=150)
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES)
    dob = models.DateField()
    phone = models.CharField(max_length=20)
    organization = models.CharField(max_length=50)

    def __unicode__(self):
        return "%s %s" %(self.first_name, self.last_name)    
    
def doc_upload_path(instance, filename):
    """
    The uploaded contacts file will be stored inside
    MEDIA_ROOT/contacts/<username>/<group_name> directory
    """
    return "contacts/%s/%s" % (instance.user.username, filename.replace(' ','-'))

class Group(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=200)
    short_code = models.CharField(max_length=30)
    contacts_filepath = models.FileField(upload_to=doc_upload_path)
    member = models.ManyToManyField(Member)
    
    def __unicode__(self):
        return self.name
    
def generate_short_code(user):
    """Function to generate short code for group
    """
    t = datetime.datetime.now()
    uts = int(time.mktime(t.timetuple()))

    if user.email not in ['', None]:
        salt = '%s%s' % (user.email, uts)
    else:
        salt = '%s%s' % (user.username, uts)

    return hashlib.sha1(salt).hexdigest()

Group/forms.py
'''
Created on Apr 8, 2013

@author: CCMT
'''
from django import forms

from Group.models import Group, generate_short_code


class GroupForm(forms.ModelForm):

    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'span3'}))

    class Meta:
        model = Group
        fields = ('name', 'description')

    def save(self, user, commit=True):
        # get the group model to add short_code field and user field values manually
        group = super(GroupForm, self).save(commit=False)
        
        # create a unique short code for group
        group.short_code = generate_short_code(user)
        
        # assign user foreign key
        group.user = user
        
        # save the form with rest of existing data.
        if commit:
            group.save()
        
        return group 
    
class ContactsUploadForm(forms.Form):

    gid = forms.IntegerField(widget=forms.HiddenInput)
    contacts_filepath = forms.FileField(
        label='Select a file',
        help_text='Only excel files are supported'
    )
        
    def save(self, commit=True):
        # get the group model to update the contacts file path and update that field
        group = super(ContactsUploadForm, self).save(commit=False)
        group.contacts_filepath = self.cleaned_data['contacts_filepath']
        
        if commit:
            group.save()

Group/views.py
'''
Created on Apr 9, 2013

@author: CCMT
'''
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.template.loader import render_to_string #, Context
from django.http import HttpResponse
from django.utils import simplejson
from django.http import Http404
#from django.views.decorators.csrf import csrf_exempt

from Group.forms import GroupForm, ContactsUploadForm
from Group.models import Group


@login_required(login_url='/auth/')
def group(request):
    groups = Group.objects.all()
    return render_to_response('group/all_groups.html',
                              {'groups':groups},
                              context_instance=RequestContext(request))


@login_required(login_url='/auth/')
def create_group(request):
    if not request.is_ajax():
        raise Http404

    if request.method == 'POST':
        form = GroupForm(data=request.POST)
        if form.is_valid():
            form.save(request.user)
            groups = Group.objects.all()
            html = render_to_string('group/groups.html', 
                                    {'groups':groups},
                                    context_instance=RequestContext(request))
        else:
            html = render_to_string('group/group_form.html',
                                    {'form':form},
                                    context_instance=RequestContext(request))

    else:
        form = GroupForm()
        html = render_to_string('group/group_form.html',
                                {'form':form},
                                context_instance=RequestContext(request))

    data = {'html': html}
    json = simplejson.dumps(data)
    return HttpResponse(json,mimetype='application/json')
    

def contacts_upload(request):
    # Handle file upload
    if request.method == 'POST':
        form = ContactsUploadForm(request.POST, request.FILES)
        # if form is valid save the file to media directory and then redirect user to 
        # view all contacts. for now we are redirecting to groups page. This is to be
        # changed later
        gid = int(request.POST.get('gid'))
        if form.is_valid():
            group = Group.objects.get(pk=gid)
            group.contacts_filepath = request.FILES['contacts_filepath']
            group.save()
            groups = Group.objects.all()
            html = render_to_string('group/groups.html', 
                                    {'groups':groups},
                                    context_instance=RequestContext(request))
        else:
            html = render_to_string('group/contacts_upload_form.html',
                                {'form':form, 'gid':gid},
                                context_instance=RequestContext(request))
    else:
        gid = request.GET.get('gid')
        form = ContactsUploadForm(initial={'gid':gid})
        html = render_to_string('group/contacts_upload_form.html',
                                {'form':form, 'gid':gid},
                                context_instance=RequestContext(request))

    data = {'html': html}
    json = simplejson.dumps(data)
    return HttpResponse(json,mimetype='application/json')

Group/templates/group/all_groups.html
{% extends "base.html" %}

{% block menu-bar %}

	<div class="navbar">
	  <div class="navbar-inner">
	    <a class="brand" href="{% url home %}">Home</a>
	    <ul class="nav">
	      <li class="dropdown">
			    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
			     Contract
			    </a>
			  <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
			    <li><a href="#" id="create-contract">Create Contract</a></li>
			    <li><a href="#" id="update-contract">Update Contract</a></li>
			  </ul>
		  </li>
	      <li class="dropdown">
	      	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
	      	Group 
	      	</a>
			  <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
			    <li><a href="#" id="create-group">Create Group</a></li>
			  </ul>
	      </li>
	      <li><a href="{% url logout %}" > Logout </a></li>
	    </ul>
	  </div>
	</div>

{% endblock %}

{% block content %}

	<h3 class="sub-header">My groups</h3>
	
	<ul class="ml0">
		{% for group in groups %}
		<li class="group-detail">
		    <p><strong>Name:</strong> {{ group.name }}</p>
		    <p><strong>Description:</strong> {{ group.description }}</p>
		    <p><a href="#" class="btn btn-small" id="contact-group-{{ group.pk }}">Update Contacts</a></p>
		</li>
		{% endfor %}
	</ul>

{% endblock %}

Group/templates/group/contacts_upload_form.html
<form action="{% url contacts-upload %}" method="post" enctype="multipart/form-data" id="contacts-upload-form">
    {% csrf_token %}
    <p>{{ form.non_field_errors }}</p>
    <p>{{ form.contacts_filepath.label_tag }} {{ form.contacts_filepath.help_text }}</p>
    <p>
        {{ form.contacts_filepath.errors }}
        {{ form.contacts_filepath }}
    </p>
    <input type="hidden" name="gid" value="{{ form.gid.value }}" id="id_gid" >
    <p><input type="submit" value="Upload" id="contact-upload-submit" /></p>
</form>

    <script> 
        // wait for the DOM to be loaded 
        $(document).ready(function() { 
            // bind 'myForm' and provide a simple callback function 
            $('#contacts-upload-form').ajaxForm(function() { 
                alert("Thank you for your comment!"); 
                
    $("#contacts-upload-submit").live('click', function (e){
 
            e.preventDefault();
            var form = $("#contacts-upload-form");
            var post_url = $(form).attr('action');
            var content = $("#content");
 
            $.ajax({
                url: post_url,
                type: 'POST',
                data: $(form).serialize(),
                dataType: 'json',
                success: function (resp){
                    $(content).html(resp.html);
                }
            });
    });
            }); 
        }); 
    </script>

Group/templates/group/group_form.html
<h2 class="sub-header">Create Group</h2>
<form id="create-group-form" class="well" action={% url create-group %} method="POST">
    {% csrf_token %}
    {{ form.as_table }}
    <br/>
    <input type="submit" class="btn btn-primary" id="create-group-submit">
</form>

Group/templates/group/groups.html
<h3 class="sub-header">My groups</h3>

<ul class="ml0">
{% for group in groups %}
<li class="group-detail">
    <p><strong>Name:</strong> {{ group.name }}</p>
    <p><strong>Description:</strong> {{ group.description }}</p>
    <p><a href="#" class="btn btn-small" >Update Contacts</a></p>
</li>
{% endfor %}
</ul>